### PR TITLE
Improving FundAFeed page  (Ready for review / merge)

### PR DESCRIPTION
**Pull request by 0xSero**
- added media queries to begin work on mobile version
- added a grid layout to main container
- seperated the hero into it's own component
- added a component (HowItWorks.js) to improve user experience
- rendered a list of links in footer (discord, support, docs, contact)

Current progress visually:

image

### CODE REVIEW

**Comment by 0xSero** [comment]
I began adding some mobile styles to help improve user experience:

image

image

**Comment by 0xSero** [comment]
## Bounty requirements complete

New UI
image

### What's different?

 - Fixed a minor bug in UI where user gets told TRB is not supported on Polygon, this was due to how the function was written: It checks for TRB balance, which will return 0 or False
 
 - Updated mobile UI to work
 
- Updated desktop by adding some links to important resources, better organizing the page and adding some relevant information

**Comment by RaynHarr** [comment]
Looks great! Couple minor things:
-Fund a price feed component cuts off right edge when window width gets reduced (see attached below)
- I'd suggest removing 'contact' footer link for redundancy sake, as 'connect' addresses that. docs & discord links are fine in this case.
Screen Shot 2022-08-10 at 12 13 53 PM
e

**Comment by 0xSero** [comment]
@RaynHarr I fixed the two issues you mentioned

**Pull request merged**
